### ISSUE TITLE
How to show only spinner 

### ISSUE THREAD

**Issue by vaibhav-jain** [jvdvleuten/angular-button-spinner#1]
@jvdvleuten great plugin. Can you tell me how to show only spinner instead of text and spinner ???

**Comment by jvdvleuten** [comment]
Can you give a code example you have and where you want to show the spinner only?

**Comment by vaibhav-jain** [comment]
@jvdvleuten Like in your example 

```
<a class="btn btn-success" ng-click="toggleLoading()" button-spinner="loading">Save</a>
```

If user clicks on save button a spinner is appended to the button text. But how I can replace the button text completely with spinner. So that whenever user clicks on save button only spinner is shown

Thanks for this handy plugin

**Comment by jvdvleuten** [comment]
There is currently no option to replace the text inside the button itself.

However, you could do it like this:

```
<a class="btn btn-success" ng-click="toggleLoading()" button-spinner="loading">
   <span ng-if="!loading">Save</span>
</a>
```

**Comment by vaibhav-jain** [comment]
thanks
